name: Lint and Build

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          CI: true
        run: npm run build

      - name: Verify output
        run: test -d dist && echo "Build output present."
